[versions]
agp = "8.5.2"
kotlin = "1.9.24"
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
webkit = "1.11.0"
swiperefresh = "1.1.0"
usbSerial = "3.8.0"

splashscreen = "1.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
usb-serial-driver = { group = "com.github.mik3y", name = "usb-serial-for-android", version.ref = "usbSerial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
